use handywork;

DROP TABLE IF EXISTS image_url;
DROP TABLE IF EXISTS job_review;
DROP TABLE IF EXISTS job_offer;
DROP TABLE IF EXISTS job;
DROP TABLE IF EXISTS user;

CREATE TABLE user (
    id BIGINT NOT NULL AUTO_INCREMENT,
    email VARCHAR(255) NOT NULL,
    city VARCHAR(255) NOT NULL,
    first_name VARCHAR(36) NOT NULL,
    last_name VARCHAR(36) NOT NULL,
    password VARCHAR(255) NOT NULL,
    profile_picture VARCHAR(255) NOT NULL,
    phone_number VARCHAR(10) NOT NULL,
    username VARCHAR(36) NOT NULL,
    PRIMARY KEY (id)
)  ENGINE=INNODB;

ALTER TABLE user
  ADD CONSTRAINT UNIQUE_EMAIL UNIQUE (email),
  ADD CONSTRAINT UNIQUE_PHONE_NUMBER UNIQUE (phone_number),
  ADD CONSTRAINT UNIQUE_USERNAME UNIQUE (username);

CREATE TABLE job (
    id BIGINT NOT NULL AUTO_INCREMENT,
    description TEXT NOT NULL,
    city VARCHAR(255) NOT NULL,
    field VARCHAR(50) NOT NULL,
    is_done BIT NOT NULL DEFAULT 0,
    job_name VARCHAR(50) NOT NULL,
    publish_date DATETIME NOT NULL,
    update_date DATETIME,
    done_by_id BIGINT,
    owner_id BIGINT NOT NULL,
    PRIMARY KEY (id)
)  ENGINE=INNODB;

ALTER TABLE job
  ADD CONSTRAINT USER_DONE_BY_FOREIGN_KEY FOREIGN KEY (done_by_id) REFERENCES user (id),
  ADD CONSTRAINT USER_OWNER_FOREIGN_KEY FOREIGN KEY (owner_id) REFERENCES user (id);
  
CREATE INDEX field_index
ON job (field);

CREATE INDEX city_index
ON job (city);

CREATE INDEX is_done_index
ON job (is_done);

CREATE TABLE image_url (
    job_id BIGINT NOT NULL,
    url VARCHAR(255) NOT NULL
)  ENGINE=INNODB;

ALTER TABLE image_url
  ADD CONSTRAINT JOB_IMAGE_FOREIGN_KEY FOREIGN KEY (job_id) REFERENCES job (id);

CREATE TABLE job_review (
    id BIGINT NOT NULL AUTO_INCREMENT,
    publish_date DATETIME NOT NULL,
    rating TINYINT NOT NULL,
    review_text TEXT NOT NULL,
    type ENUM('JOB_REVIEW', 'USER_REVIEW') NOT NULL,
    update_date DATETIME,
    job_id BIGINT NOT NULL,
    by_user_id BIGINT NOT NULL,
    on_user_id BIGINT NOT NULL,
    PRIMARY KEY (id)
)  ENGINE=INNODB;

ALTER TABLE job_review
  ADD CONSTRAINT JOB_REVIEW_FOREIGN_KEY FOREIGN KEY (job_id) REFERENCES job (id),
  ADD CONSTRAINT BY_USER_FOREIGN_KEY FOREIGN KEY (by_user_id) REFERENCES user (id),
  ADD CONSTRAINT ON_USER_FOREIGN_KEY FOREIGN KEY (on_user_id) REFERENCES user (id);

CREATE TABLE job_offer (
    id BIGINT NOT NULL AUTO_INCREMENT,
    user_id BIGINT NOT NULL,
    job_id BIGINT NOT NULL,
    suggested_amount INT NOT NULL,
    accepted BIT NOT NULL DEFAULT 0,
    rejected BIT NOT NULL DEFAULT 0,
    PRIMARY KEY (id)
)  ENGINE=INNODB;

ALTER TABLE job_offer
  ADD CONSTRAINT JOB_JOB_OFFER_FOREIGN_KEY FOREIGN KEY (job_id) REFERENCES job (id),
  ADD CONSTRAINT USER_JOB_OFFER_FOREIGN_KEY FOREIGN KEY (user_id) REFERENCES user (id);

CREATE INDEX accepted_index
ON job_offer (accepted);

CREATE INDEX rejected_index
ON job_offer (rejected);